### DISCUSSION TITLE
How can I connect to rds  ?

### DISCUSSION THREAD

**Discussion by youssefmaher99** [mediacms-io/mediacms#1099] [General]
As the title states, I have an RDS PostgreSQL instance. After updating the docker-compose.yaml file, I made the following changes:
- Removed the DB service
- Added PostgreSQL RDS environment variables to all services
- Updated cms/settings.py, cms/local_settings.py, and deploy/local_settings.py with the correct RDS values
The migration service works correctly, but the web service fails, resulting in a 500 server status.
If anyone has experience connecting to RDS, I would really appreciate your help.

**Comment by mgogoulos** [comment]
if the migration service works correctly, it means that connection to RDS is succesful, so the web service should be able to connect to. What is the log message, can you check with docker logs?

**Reply by youssefmaher99** [reply]
this is my docker-compose.yaml file
```
version: "3"
services:
  migrations:
    image: mediacms-custom6:latest
    volumes:
      - ./:/home/mediacms.io/mediacms/
    environment:
      ENABLE_UWSGI: 'no'
      ENABLE_NGINX: 'no'
      ENABLE_CELERY_SHORT: 'no'
      ENABLE_CELERY_LONG: 'no'
      ENABLE_CELERY_BEAT: 'no'
      ADMIN_USER: 'admin'
      ADMIN_EMAIL: 'admin@localhost'
      ADMIN_PASSWORD: 'admin'
      POSTGRES_HOST: '********'
      POSTGRES_PORT: '5432'
      POSTGRES_DB: 'mediacms'
      POSTGRES_USER: '********'
      POSTGRES_PASSWORD: '********'
      PGSSLMODE: "require"
    command: "./deploy/docker/prestart.sh"
    restart: on-failure
    depends_on:
      redis:
        condition: service_healthy
  web:
    image: mediacms-custom6:latest
    deploy:
      replicas: 1
    ports:
      - "80:80"
    volumes:
      - ./:/home/mediacms.io/mediacms/
    environment:
      ENABLE_CELERY_BEAT: 'no'
      ENABLE_CELERY_SHORT: 'no'
      ENABLE_CELERY_LONG: 'no'
      ENABLE_MIGRATIONS: 'no'
      POSTGRES_HOST: ''********''
      POSTGRES_PORT: '5432'
      POSTGRES_DB: 'mediacms'
      POSTGRES_USER: ''********''
      POSTGRES_PASSWORD: ''********''
      PGSSLMODE: "require"
    depends_on:
      - migrations
  celery_beat:
    image: mediacms-custom6:latest
    volumes:
      - ./:/home/mediacms.io/mediacms/
      - ./global-bundle.pem:/etc/ssl/certs/global-bundle.pem
    environment:
      ENABLE_UWSGI: 'no'
      ENABLE_NGINX: 'no'
      ENABLE_CELERY_SHORT: 'no'
      ENABLE_CELERY_LONG: 'no'
      ENABLE_MIGRATIONS: 'no'
      POSTGRES_HOST: ''********''
      POSTGRES_PORT: '5432'
      POSTGRES_DB: 'mediacms'
      POSTGRES_USER: ''********''
      POSTGRES_PASSWORD: ''********''
      PGSSLMODE: "require"
    depends_on:
      - redis
  celery_worker:
    image: mediacms-custom6:latest
    deploy:
      replicas: 1
    volumes:
      - ./:/home/mediacms.io/mediacms/
    environment:
      ENABLE_UWSGI: 'no'
      ENABLE_NGINX: 'no'
      ENABLE_CELERY_BEAT: 'no'
      ENABLE_MIGRATIONS: 'no'
      POSTGRES_HOST: ''********''
      POSTGRES_PORT: '5432'
      POSTGRES_DB: 'mediacms'
      POSTGRES_USER: ''********''
      POSTGRES_PASSWORD: ''********''
      PGSSLMODE: "require"
    depends_on:
      - migrations
  redis:
    image: "redis:alpine"
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 30s
      timeout: 10s
      retries: 3
```
