### DISCUSSION TITLE
Optimize docker installation which does not map the entire repo

### DISCUSSION THREAD

**Discussion by ihaettypo** [mediacms-io/mediacms#1252] [Q&A] [answered]
First off, thanks for this great project!

While trying to spin it up, I noticed the Docker Compose file bind-mounts the entire repo into the container, which is uncommon, and perhaps is also bringning confusions to other people eager to try this project out. As far as I know, normally the docker image already contains all source code / packages necessary to run, so only data folder needs to be bind-mounted for persistence mostly.

Is there a specific reason for this approach? Just curious if it’s strictly necessary for things to work. And if not, perhaps standardize the installation which only bind mount the directories that needs to be persisted? I guess people will understand this better.

The second thing that might be confusing is the "migrations" service, is this necessary for fresh install too? Sounds like it is used only when migrating from a lower incompatible version?

**Comment by mgogoulos** [comment]
Hi 

The entire Docker setup is working but needs optimizations. Mounting the code is not necessary, but is handy if you make changes. The migrations service is `django migrations`, which needs to be run because there might be changes in the DB schema. So it has to be there, but I agree on what you say that lots of things have to be more clear! Another thing is that there used to be many docker compose files for providing examples as named volumes, or setting up https sites with letsenctypt/nginx/acme. They were moved to a folder for this because they made maintaning them tricky. Now they will become deprecated and eventually they should be removed too. 

Speaking about this, what is your prefered environment for deployment, Docker Compose, Kubernetes, or something else?

**Comment by ihaettypo** [comment, marked as answer]
I finally had time to spin it up. I'm using docker compose, and for whoever also wants to spin it up without mapping the entire repo, and as a standalone container, I'm sharing my example below, hope this can help:

```yaml
services:
  web:
    image: mediacms/mediacms:latest
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - /path/to/local_settings.py:/home/mediacms.io/mediacms/deploy/docker/local_settings.py # This is your configuartion file
      - media_store:/home/mediacms.io/mediacms/media_files/
      - static_store:/home/mediacms.io/mediacms/static/
    environment:
      FRONTEND_HOST: <host>
      # Admin creation (only effective for first run)
      ADMIN_USER: admin
      ADMIN_EMAIL: <admin-email>
      ADMIN_PASSWORD: <admin-password>
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
  db:
    image: postgres:17.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    environment:
      POSTGRES_USER: mediacms
      POSTGRES_PASSWORD: mediacms
      POSTGRES_DB: mediacms
      TZ: Europe/London
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}", "--host=db", "--dbname=$POSTGRES_DB", "--username=$POSTGRES_USER"]
      interval: 30s
      timeout: 10s
      retries: 5
  redis:
    image: "redis:alpine"
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
  media_store:
  static_store:
``` 

And FYI, the standalone container consumes around 1.5 GB RAM on idle.
