### DISCUSSION TITLE
Docker install: What's the correct way to store the media directory outside the mediacms home?

### DISCUSSION THREAD

**Discussion by DecaTec** [mediacms-io/mediacms#215] [Q&A]
Due to storage requirements, I want to store all the media files (folder `media_files`) outside the mediacms home on a Docker install. E.g. the media files should be stored on a mounted NFS share (mountet as `/mnt/nfs/mediacms/media_files`.

I've now tried it with modifying the `docker-compose.yaml` (see the added volumes for 'web' and 'celery_worker'):

```
version: "3"

services:
  migrations:
    image: mediacms/mediacms:latest
    volumes:
      - ./:/home/mediacms.io/mediacms/
    environment:
      ENABLE_UWSGI: 'no'
      ENABLE_NGINX: 'no'
      ENABLE_CELERY_SHORT: 'no'
      ENABLE_CELERY_LONG: 'no'
      ENABLE_CELERY_BEAT: 'no'
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
  web:
    image: mediacms/mediacms:latest
    deploy:
      replicas: 1
    ports:
      - "8008:80"
    volumes:
      - ./:/home/mediacms.io/mediacms/
      - /mnt/nfs/mediacms/media_files/:/home/mediacms.io/mediacms/media_files
    environment:
      ENABLE_CELERY_BEAT: 'no'
      ENABLE_CELERY_SHORT: 'no'
      ENABLE_CELERY_LONG: 'no'
      ENABLE_MIGRATIONS: 'no'
    depends_on:
      - migrations
  celery_beat:
    image: mediacms/mediacms:latest
    volumes:
      - ./:/home/mediacms.io/mediacms/
    environment:
      ENABLE_UWSGI: 'no'
      ENABLE_NGINX: 'no'
      ENABLE_CELERY_SHORT: 'no'
      ENABLE_CELERY_LONG: 'no'
      ENABLE_MIGRATIONS: 'no'
    depends_on:
      - redis
  celery_worker:
    image: mediacms/mediacms:latest
    deploy:
      replicas: 1
    volumes:
      - ./:/home/mediacms.io/mediacms/
      - /mnt/nfs/mediacms/media_files/:/home/mediacms.io/mediacms/media_files 
    environment:
      ENABLE_UWSGI: 'no'
      ENABLE_NGINX: 'no'
      ENABLE_CELERY_BEAT: 'no'
      ENABLE_MIGRATIONS: 'no'
    depends_on:
      - migrations
  db:
    image: postgres
    volumes:
      - ../postgres_data:/var/lib/postgresql/data/
    restart: always
    environment:
      POSTGRES_USER: mediacms
      POSTGRES_PASSWORD: mediacms
      POSTGRES_DB: mediacms
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mediacms"]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: "redis:alpine"
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 30s
      timeout: 10s
      retries: 3
```

This seems to work, but I still have a few questions:
* Is there a better/official way to achieve this?
* Do only the containers 'web' and 'celery_worker' need access to the `media_files` directory or should the corresponding volume be added to the other containers too?

And another offtopic question:
Why the volume for PostgreSQL is not inside the working dir of mediacms?

That's part of the `docker-compose.yaml`:
```
- ../postgres_data:/var/lib/postgresql/data/
```

Wouldn't this be sufficient:
```
- ./postgres_data:/var/lib/postgresql/data/
```
