### DISCUSSION TITLE
how to install on different port?

### DISCUSSION THREAD

**Discussion by mohmafia** [mediacms-io/mediacms#304] [Q&A]
how to install on docker with different port then 80 and 443 as the ports are already in use
any help would be appreciated thanks

**Comment by mgogoulos** [comment]
The default docker-compose file (docker-compose.yaml) doesn't start on 443/https but only on 80. 
If you're using this, edit and set a new port instead of 80:80. For example, if you want the application to load on port 1233, set it like this:

```
  web:
    image: mediacms/mediacms:latest
    deploy:
      replicas: 1
    ports:
      - "1233:80"
```

and restart docker-compose for the change to take effect

```
docker-compose down ; docker-compose up
```

Now MediaCMS should load on http://ip:1233
