### DISCUSSION TITLE
Selenium

### DISCUSSION THREAD

**Discussion by GeorgiDimitrov87** [mediacms-io/mediacms#341] [General]
Selenium was giving an error when I launched docker-compose.dev.yaml so I changed it like this and it stopped.
```
  selenium:
      image: selenium/standalone-firefox-debug
      container_name: btce-selenium
      ports:
        - "4444:4444"
        - "5900:5900"

  # selenium_hub:
  #   container_name: selenium_hub
  #   image: selenium/hub
  #   ports:
  #     - "4444:4444"
  #   # depends_on:
  #   #   - web

  # selenium_chrome:
  #   container_name: selenium_chrome
  #   image: selenium/node-chrome-debug
  #   environment:
  #     - HUB_PORT_4444_TCP_ADDR=selenium_hub
  #     - HUB_PORT_4444_TCP_PORT=4444
  #   ports:
  #     - "5900:5900"
  #   depends_on:
  #     - selenium_hub
```
