### DISCUSSION TITLE
How to fix docker-compose.yaml error ?

### DISCUSSION THREAD

**Discussion by Dan1ell** [mediacms-io/mediacms#60] [Q&A] [answered]
Hi community,

I'm receiving the following error while installing mediacms:

> dan1ell@dan1ell:~/mediacms$ docker-compose build && docker-compose up
> ERROR: The Compose file './docker-compose.yaml' is invalid because:
> services.web.build contains unsupported option: 'target'
> services.migrations.depends_on contains an invalid type, it should be an array

I can see the 2 offending lines in the yaml file, but I'm not sure what to change them into.

```
services:
  migrations:
    image: mediacms:latest
    volumes:
      - ./:/home/mediacms.io/mediacms/
    environment:
      ENABLE_UWSGI: 'no'
      ENABLE_NGINX: 'no'
      ENABLE_CELERY_SHORT: 'no'
      ENABLE_CELERY_LONG: 'no'
      ENABLE_CELERY_BEAT: 'no'
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
  web:
    build:
      context: .
      target: runtime-image
    image: mediacms:latest

```

Running Docker 19.03.8 on Ubuntu 20.04 in VirtualBox 6.1.18 r142142 on a Mac 11.2.1
What should I do here?
