### DISCUSSION TITLE
Docker compose installation tutorial for Synology NAS

### DISCUSSION THREAD

**Discussion by mgogoulos** [mediacms-io/mediacms#651] [Feature Requests]
### Discussed in https://github.com/mediacms-io/mediacms/discussions/282

<div type='discussions-op-text'>

<sup>Originally posted by **EricGuic** August 24, 2021</sup>
Hi (from a french follower),
I'm not a developper, and as a growing number of people, I start to take back control over my data using simple services that I host on my Synology NAS using Docker.
Folowing tutorials (likes the one provided by [Marius Hosting](https://mariushosting.com/), or [Rusty](https://www.blackvoid.club/) or many other...) I've successfully installed Portainer to manage simple services like Snapdrop, Tiny RSS, AdGuardHome...

So now, I want to host my own video platform (I'm a director, and don't want to use Youtube or Vimeo, and want to try MediaCMS to host my files, and generate multiples resolution and the embed code needed to add those videos to my blogs under Ghost and Wordpress).

But in your documentation or in the medium post you write, I see installation process that are too complicated for the kind of user I represent.

Is there a way to write a guide, that will describe : 

- how to fully install MediaCMS using the stack feature inside Portainer (the compose file is written directly inside the Portainer web UI, and is relatively simple to update the image later or to edit the configuration variable inside this compose syntax without the need to type ssh command)
- how to map the directory so the media files can be store outside the container, on a volume on the NAS (this is for example what I do for my Plex Media Server : the app is inside a container in /docker/pms/ and the media are inside multiple folders inside media/movie or media/music and so on.

Thanks per advance if you can provide this sort of help.

Best regards from France. Eric</div>

**Comment by mgogoulos** [comment]
Hi @EricGuic , I have converted this to an issue. Added the help wanted label and hope some contributor can handle this!

Best
Markos

**Comment by scyto** [comment]
@ericguic 

This is not going to be simple to get working on synology due to the design decision to use a gitclone of mediacms outside of the container (when what should have been done was to have it inside the containers with just the config files and media outside.

I just wrote a breadcrumb trail for a friend trying to get all of this working.


**assumes you have docker and docker-compose installed**
  1. on the host OS navigate to the parent location you want the mediacms app and content to live
  2. git clone the project then `cd mediacms`
  3. edit docker-compose.yaml to look like this https://pastebin.com/aTmaBarU  change the port as needed and the password to something else
  4. setup a NGIX proxy like NPM to point cms.mydomain.com to dockerhost<ip:port> (aka the port you set in 3 above) make sure you create a http NPM host using a cert
  5. in the mediacms dir edit ./deploy/docker/local_settings.py and change the FRONTEND_HOST = 'http://localhost' to reflect whatever https://cms.mydomain.com/ you created in step 4
  6. docker-compose up 

in theory you could use this taml content inside portainers UI, you would need to amend the volume paths to be absolute not relative,

things i found:
1. the docker-compose.yaml is syntactically wrong for the version it has, it will fail (conditions are no longer allowed) - the pastebin link abve is a known good yaml
2. for some reason even though the web1 nginx service seems to be only listening on 80 it keeps trying to set the protocol to SSL - rather than dig into the why i mitigated by fronting with my nginx reverse proxy

Good luck, this is not a simple or canonical docker implementation.
I can't provide more help as beyond doing a poc to help out a friend i have no use for this CMS)

**Comment by sgrasser** [comment]
I know this discussion is a little old but I managed to get a portainer stack together that works as of May 2025:

```
`version: "3"
services:
  migrations:
    image: mediacms/mediacms:latest
    container_name: mediacms_migrations
    volumes:
      - media_store:/home/mediacms.io/mediacms/media_files/
      - static_store:/home/mediacms.io/mediacms/static/
      - /volume1/docker/mediacms/local_settings_custom.py:/home/mediacms.io/mediacms/deploy/docker/local_settings.py
    environment:
      ENABLE_UWSGI: 'no'
      ENABLE_NGINX: 'no'
      ENABLE_CELERY_SHORT: 'no'
      ENABLE_CELERY_LONG: 'no'
      ENABLE_CELERY_BEAT: 'no'
      ADMIN_USER: 'admin'
      ADMIN_EMAIL: 'admin@example.com'
      ADMIN_PASSWORD: 'mypassword'
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: mediacms
      DATABASE_PASSWORD: mediacms
      REDIS_HOST: redis
      REDIS_PORT: 6379
      TZ: Europe/Zurich
    command: "./deploy/docker/prestart.sh"
    restart: on-failure
    depends_on:
      - redis
      - db

  web:
    image: mediacms/mediacms:latest
    container_name: mediacms_web
    ports:
      - "8999:80"
    volumes:
      - media_store:/home/mediacms.io/mediacms/media_files/
      - static_store:/home/mediacms.io/mediacms/static/
      - /volume1/docker/mediacms/local_settings_custom.py:/home/mediacms.io/mediacms/deploy/docker/local_settings.py
    environment:
      ENABLE_CELERY_BEAT: 'no'
      ENABLE_CELERY_SHORT: 'no'
      ENABLE_CELERY_LONG: 'no'
      ENABLE_MIGRATIONS: 'no'
      ENABLE_NGINX: 'yes'
      ENABLE_UWSGI: 'yes'
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: mediacms
      DATABASE_PASSWORD: mediacms
      REDIS_HOST: redis
      REDIS_PORT: 6379
      TZ: Europe/Zurich
    restart: unless-stopped
    depends_on:
      - migrations

  celery_beat:
    image: mediacms/mediacms:latest
    container_name: mediacms_celery_beat
    volumes:
      - media_store:/home/mediacms.io/mediacms/media_files/
      - static_store:/home/mediacms.io/mediacms/static/
      - /volume1/docker/mediacms/local_settings_custom.py:/home/mediacms.io/mediacms/deploy/docker/local_settings.py
    environment:
      ENABLE_UWSGI: 'no'
      ENABLE_NGINX: 'no'
      ENABLE_CELERY_SHORT: 'no'
      ENABLE_CELERY_LONG: 'no'
      ENABLE_CELERY_BEAT: 'yes'
      ENABLE_MIGRATIONS: 'no'
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: mediacms
      DATABASE_PASSWORD: mediacms
      REDIS_HOST: redis
      REDIS_PORT: 6379
      TZ: Europe/Zurich
    restart: unless-stopped
    depends_on:
      - redis
      - migrations

  celery_worker_short:
    image: mediacms/mediacms:latest
    container_name: mediacms_worker_short
    volumes:
      - media_store:/home/mediacms.io/mediacms/media_files/
      - static_store:/home/mediacms.io/mediacms/static/
      - /volume1/docker/mediacms/local_settings_custom.py:/home/mediacms.io/mediacms/deploy/docker/local_settings.py
    environment:
      ENABLE_UWSGI: 'no'
      ENABLE_NGINX: 'no'
      ENABLE_CELERY_BEAT: 'no'
      ENABLE_CELERY_SHORT: 'yes'
      ENABLE_CELERY_LONG: 'no'
      ENABLE_MIGRATIONS: 'no'
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: mediacms
      DATABASE_PASSWORD: mediacms
      REDIS_HOST: redis
      REDIS_PORT: 6379
      TZ: Europe/Zurich
    restart: unless-stopped
    depends_on:
      - migrations

  celery_worker_long:
    image: mediacms/mediacms:latest
    container_name: mediacms_worker_long
    volumes:
      - media_store:/home/mediacms.io/mediacms/media_files/
      - static_store:/home/mediacms.io/mediacms/static/
      - /volume1/docker/mediacms/local_settings_custom.py:/home/mediacms.io/mediacms/deploy/docker/local_settings.py
    environment:
      ENABLE_UWSGI: 'no'
      ENABLE_NGINX: 'no'
      ENABLE_CELERY_BEAT: 'no'
      ENABLE_CELERY_SHORT: 'no'
      ENABLE_CELERY_LONG: 'yes'
      ENABLE_MIGRATIONS: 'no'
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: mediacms
      DATABASE_PASSWORD: mediacms
      REDIS_HOST: redis
      REDIS_PORT: 6379
      TZ: Europe/Zurich
    restart: unless-stopped
    depends_on:
      - migrations

  db:
    image: postgres:13-alpine
    container_name: mediacms_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    environment:
      POSTGRES_USER: mediacms
      POSTGRES_PASSWORD: mediacms
      POSTGRES_DB: mediacms
      TZ: Europe/Zurich
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mediacms"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    container_name: mediacms_redis
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

# Use named Volumes, but initialize with existing data
volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /volume1/docker/mediacms/db_data
  media_store:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /volume1/docker/mediacms/media_data
  static_store:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /volume1/docker/mediacms/static_data
```
