### ISSUE TITLE
can not change MEDIA_ROOT to an USB drive

### ISSUE THREAD

**Issue by SDFTDusername** [mediacms-io/mediacms#1091]
**Describe the issue**
I want to store all media and their encoded files on my USB drive, but when I try to do that I can't upload videos anymore.

I tried setting ``MEDIA_ROOT`` in ``/home/mediacms.io/mediacms/cms/settings.py`` to ``/mnt/f/media_files/``
and tried mounting the usb to ``/home/mediacms.io/mediacms/media_files``

but neither worked. when I try to upload something, it retries twice and then fails. it only works if ``MEDIA_ROOT`` points at ``/home/mediacms.io/mediacms/media_files`` (default) without the usb mounted to that path.

I tried this with the USB formatted to exFAT and NTFS

**Expected behavior**
it should work like normal.

**Environment**
 - OS: WSL 2 with Ubuntu 22
 - Installation method: single server install
 - Browser: Microsoft Edge

**Comment by yatesdr** [comment]
Did you check the permissions on the mount location?   The docker install needs write access to whatever you're trying to write.

> cd /mnt/f
> ls -lah 
check the permissions assigned, if they're 755 for your user / your password, mediaCMS won't be able to write there as it runs under some other user typically.
> chmod 777 media_files

If that fixes it, you know it's a permissions issue with your mount.   It's not really a great idea to just leave it as 777, so you'll have to figure out what user and group mediacms is running as and change to 775 and chgrp to the appropriate permissions.

**Comment by SDFTDusername** [comment]
when i run ``ls -lah``, it says that the ``media_files`` directory is ``drwxrwxrwx``, which means full permission, and running ``chmod 777 media_files`` doesn't change anything.
also it writes just fine. i tried uploading an image and even though the website says it fails, i can see the image at ``/mnt/f/media_files/uploads/{random-uuid}``
but i don't see the videos of failed uploads at ``/mnt/f/media_files/original/user/{username}`` and ``/mnt/f/media_files/encoded/{num}/{username}``

**Comment by yatesdr** [comment]
That almost sounds like it's writing with permissions it can't read.   Did you check the permissions that got set on the "failed" image upload that appeared?   If those are okay, then you may need to also check your postgres_data directory and make sure the database writes aren't failing for some reason.

I have had a bunch of trouble with permissions trying to run it for development with docker on MacOS that I was unable to solve, but it ran properly on ubuntu server in docker as a generic user.

**Comment by SDFTDusername** [comment]
where's the ``postgres_data`` directory? the files also have full permissions.
also i checked and i'm able to see the failed video uploads, i just didn't check the right directory

**Comment by yatesdr** [comment]
On my system, it created it in the root folder, but I'm running a docker instance.   It should be set in your config somewhere, check there.   Aside from that, I'm out of ideas, will have to wait for someone more knowledgeable to come along if you can't get it sorted.

**Comment by SDFTDusername** [comment]
there is no ``postgres_data`` directory. i ran ``find / -type d -name 'postgres_data'`` but nothing was found, maybe that directory is only for docker instances?

**Comment by gimail** [comment]
Installing Docker on WSL (Windows Subsystem for Linux) and deploying MediaCMS can be done using the following steps. Here we will assume that you are using WSL 2 and the Ubuntu distribution. If WSL 2 is not configured yet, make sure that you have done so before you start installing Docker.

       Step 1: Make sure that WSL 2 is installed and configured
1. Open PowerShell as an administrator and run:
            bash
   wsl --set-default-version 2
            
2. Make sure that you have the Ubuntu distribution installed. If not, install it through the Microsoft Store.
       Step 2: Install Docker on Ubuntu in WSL
1. Open your Ubuntu session in WSL.
2. Update the package list and install the necessary dependencies:
            bash
   sudo apt update
   sudo apt install apt-transport-https ca-certificates curl software-properties-common
            
3. Install the Docker GPG key:
            bash
   curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
            
4. Add the Docker repository to the list of package sources:
            bash
   echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list
            
5. Update the package list again:
            bash
   sudo apt update
            
6. Install Docker:
            bash
   sudo apt install docker-ce
            
7. After installing Docker, run the Docker daemon:
            bash
   sudo service docker start
            
       Step 3: Configure Docker to work without sudo (optional)
If you want to run Docker without using `sudo`, add your user to the Docker group.
         bash
sudo usermod -aG docker $USER
         
After executing this command, you will need to log out and log in again for the changes to take effect.
       Step 4: Install Docker Compose (optional)
If MediaCMS requires Docker Compose, install it:
1. Install Docker Compose:
            bash
   sudo apt install docker-compose
            
2. Check the installation:
            bash
   docker-compose --version
            
       Step 5: Install MediaCMS
Now you are ready to install MediaCMS. Create a directory in Windows in another drive for your project and navigate to it and copy mediacms there:
         in WSL Ubuntu, go to the directory in Windows 
cd /mnt/d/mediacms
         
Edit the 'docker-compose' file.yml` with settings for MediaCMS. Sample content:
version: "3"
services:
  migrations:
    image: mediacms/mediacms:latest
    volumes:
      - ./:/home/mediacms.io/mediacms/
    environment:
      ENABLE_UWSGI: 'no'
      ENABLE_NGINX: 'no'
      ENABLE_CELERY_SHORT: 'no'
      ENABLE_CELERY_LONG: 'no'
      ENABLE_CELERY_BEAT: 'no'
      ADMIN_USER: 'admin'
      ADMIN_EMAIL: 'admin@localhost'
      ADMIN_PASSWORD: 'admin'
    command: "./deploy/docker/prestart.sh"
    restart: on-failure
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
  web:
    image: mediacms/mediacms:latest
    deploy:
      replicas: 1
    ports:
      - "80:80"
    volumes:
      - /mnt/d/mediacms:/home/mediacms.io/mediacms/
    environment:
      ENABLE_CELERY_BEAT: 'no'
      ENABLE_CELERY_SHORT: 'no'
      ENABLE_CELERY_LONG: 'no'
      ENABLE_MIGRATIONS: 'no'
    depends_on:
      - migrations
  celery_beat:
    image: mediacms/mediacms:latest
    volumes:
      - /mnt/d/mediacms:/home/mediacms.io/mediacms/
    environment:
      ENABLE_UWSGI: 'no'
      ENABLE_NGINX: 'no'
      ENABLE_CELERY_SHORT: 'no'
      ENABLE_CELERY_LONG: 'no'
      ENABLE_MIGRATIONS: 'no'
    depends_on:
      - redis
  celery_worker:
    image: mediacms/mediacms:latest
    deploy:
      replicas: 1
    volumes:
      - /mnt/d/mediacms:/home/mediacms.io/mediacms/
    environment:
      ENABLE_UWSGI: 'no'
      ENABLE_NGINX: 'no'
      ENABLE_CELERY_BEAT: 'no'
      ENABLE_MIGRATIONS: 'no'
    depends_on:
      - migrations
  db:
    image: postgres:15.2-alpine
    volumes:
      - ../postgres_data:/var/lib/postgresql/data/
    restart: always
    environment:
      POSTGRES_USER: mediacms
      POSTGRES_PASSWORD: mediacms
      POSTGRES_DB: mediacms
      PGUSER: mediacms
      TZ: Europe/London
    healthcheck:
      test: ["CMD-SHELL",  "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}", "--host=db", "--dbname=$POSTGRES_DB", "--username=$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: "redis:alpine"
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 30s
      timeout: 10s
      retries: 3
- ../postgres_data:/var/lib/postgresql/data/ - to your preference
If the command `sudo chown -R 999:999 ../postgres_data` does not change the owner and the group remains `root:root`, this may happen for one of the following reasons:
1. The system does not allow you to change the owner: Some file systems, in particular, states such as NTFS or FAT, may not support UNIX-like permissions and owners. If you are running on Windows and using WSL (Windows Subsystem for Linux), this may be a problem.
2. Docker Desktop and WSL: If you use Docker on Windows via WSL, rights errors may occur due to the peculiarities of the WSL file system.
    Possible solutions
Open the etc/wsl.conf file, if it is missing, create it. Add the configuration:
[autumount]
enabled = true
options="metadata,umask=22,fmask=11"
sudo chmod -R 777 /mnt/d/mediacms
wsl --shutdown
 1. Try to change the access rights:
You can change the access rights so that all users can write to the directory, although this is not the best way from a security point of view:
   bash
sudo chmod -R 777 ../postgres_data
   
After that, check the operation of the container.
docker start $(docker ps -aq) starting all containers after installing MediaCMS

**Comment by mgogoulos** [comment]
> That almost sounds like it's writing with permissions it can't read. Did you check the permissions that got set on the "failed" image upload that appeared? If those are okay, then you may need to also check your postgres_data directory and make sure the database writes aren't failing for some reason.
> 
> I have had a bunch of trouble with permissions trying to run it for development with docker on MacOS that I was unable to solve, but it ran properly on ubuntu server in docker as a generic user.

i don't have much experience with MacOS but if there are specific suggestions to improve things it would be great! I'm mainly using/developing in Linux where things run smoothly, however I see there are many people in MacOS and Windows too

**Comment by nigel-daniels** [comment]
Is there any advice on changing the paths for the `media_files`? I cannot get it to work and need the storage to be on a separate volume (NAS using `ext4`)? I am using a Mac and the system ran fine when the storage was the `media_files` directory created internally, but when I change it to use an external mapping I can upload files but not convert them. In the UI I see the file progress as it uploads, then it goes into processing but eventually returns `Upload failed`. Looking at the directory ownership the user and group are correct and the permissions are 777 anyway.

In the the logs I see the below, so it looks like something is not cleaning up correctly:

```
OSError: [Errno 39] Directory not empty: '/home/mediacms.io/mediacms/media_files/chunks/c88833ed-9b1e-43a2-b5c9-c5f0294eac24'
Internal Server Error: /fu/upload/
Traceback (most recent call last):
  File "/home/mediacms.io/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/mediacms.io/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mediacms.io/lib/python3.13/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mediacms.io/mediacms/uploader/views.py", line 49, in dispatch
    return super(FineUploaderView, self).dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mediacms.io/lib/python3.13/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/mediacms.io/lib/python3.13/site-packages/django/views/generic/edit.py", line 151, in post
    return self.form_valid(form)
           ~~~~~~~~~~~~~~~^^^^^^
  File "/home/mediacms.io/mediacms/uploader/views.py", line 55, in form_valid
    self.upload.combine_chunks()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/mediacms.io/mediacms/uploader/fineuploader.py", line 111, in combine_chunks
    shutil.rmtree(self._abs_chunks_path)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/shutil.py", line 763, in rmtree
    _rmtree_safe_fd(stack, onexc)
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/shutil.py", line 707, in _rmtree_safe_fd
    onexc(func, path, err)
    ~~~~~^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/shutil.py", line 658, in _rmtree_safe_fd
    os.rmdir(name, dir_fd=dirfd)
    ~~~~~~~~^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 39] Directory not empty: '/home/mediacms.io/mediacms/media_files/chunks/c88833ed-9b1e-43a2-b5c9-c5f0294eac24'
Internal Server Error: /fu/upload/
Traceback (most recent call last):
  File "/home/mediacms.io/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/mediacms.io/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/mediacms.io/lib/python3.13/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mediacms.io/mediacms/uploader/views.py", line 49, in dispatch
    return super(FineUploaderView, self).dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mediacms.io/lib/python3.13/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/mediacms.io/lib/python3.13/site-packages/django/views/generic/edit.py", line 151, in post
    return self.form_valid(form)
           ~~~~~~~~~~~~~~~^^^^^^
  File "/home/mediacms.io/mediacms/uploader/views.py", line 55, in form_valid
    self.upload.combine_chunks()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/mediacms.io/mediacms/uploader/fineuploader.py", line 111, in combine_chunks
    shutil.rmtree(self._abs_chunks_path)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/shutil.py", line 763, in rmtree
    _rmtree_safe_fd(stack, onexc)
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/shutil.py", line 707, in _rmtree_safe_fd
    onexc(func, path, err)
    ~~~~~^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/shutil.py", line 658, in _rmtree_safe_fd
    os.rmdir(name, dir_fd=dirfd)
    ~~~~~~~~^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 39] Directory not empty: '/home/mediacms.io/mediacms/media_files/chunks/c88833ed-9b1e-43a2-b5c9-c5f0294eac24'
```

Here is the `docker-compose.yaml` I am using, is this the correct way to do this or is there a setting I missed in the `deploy\docker\local_settings.py`?

```
version: "3"

services:
  migrations:
    image: mediacms/mediacms:latest
    volumes:
      - ./:/home/mediacms.io/mediacms/
    environment:
      ENABLE_UWSGI: 'no'
      ENABLE_NGINX: 'no'
      ENABLE_CELERY_SHORT: 'no'
      ENABLE_CELERY_LONG: 'no'
      ENABLE_CELERY_BEAT: 'no'
      ADMIN_USER: 'admin'
      ADMIN_EMAIL: 'admin@localhost'
      ADMIN_PASSWORD: '********'
    command: "./deploy/docker/prestart.sh"
    restart: on-failure
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
  web:
    image: mediacms/mediacms:latest
    deploy:
      replicas: 1
    ports:
      - "80:80"
    volumes:
      - ./:/home/mediacms.io/mediacms/
      - /Volumes/media/media_files/:/home/mediacms.io/mediacms/media_files/
    environment:
      ENABLE_CELERY_BEAT: 'no'
      ENABLE_CELERY_SHORT: 'no'
      ENABLE_CELERY_LONG: 'no'
      ENABLE_MIGRATIONS: 'no'
    depends_on:
      - migrations
  celery_beat:
    image: mediacms/mediacms:latest
    volumes:
      - ./:/home/mediacms.io/mediacms/
      - /Volumes/media/media_files/:/home/mediacms.io/mediacms/media_files/
    environment:
      ENABLE_UWSGI: 'no'
      ENABLE_NGINX: 'no'
      ENABLE_CELERY_SHORT: 'no'
      ENABLE_CELERY_LONG: 'no'
      ENABLE_MIGRATIONS: 'no'
    depends_on:
      - redis
  celery_worker:
    image: mediacms/mediacms:latest
    deploy:
      replicas: 1
    volumes:
      - ./:/home/mediacms.io/mediacms/
      - /Volumes/media/media_files/:/home/mediacms.io/mediacms/media_files/
    environment:
      ENABLE_UWSGI: 'no'
      ENABLE_NGINX: 'no'
      ENABLE_CELERY_BEAT: 'no'
      ENABLE_MIGRATIONS: 'no'
    depends_on:
      - migrations
  db:
    image: postgres:17.2-alpine
    volumes:
      - /Volumes/media/postgres_data:/var/lib/postgresql/data/
    restart: always
    environment:
      POSTGRES_USER: mediacms
      POSTGRES_PASSWORD: mediacms
      POSTGRES_DB: mediacms
      TZ: US/Pacific
    healthcheck:
      test: ["CMD-SHELL",  "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}", "--host=db", "--dbname=$POSTGRES_DB", "--username=$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: "redis:alpine"
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 30s
      timeout: 10s
      retries: 3
```

**Comment by gimail** [comment]
Your path is not defined NAS in Linux: cd /mnt and then run the ls command.
sudo apt update && sudo apt install nfs-common cifs-utils -y  # Debian/Ubuntu
sudo dnf install nfs-utils cifs-utils -y     # Fedora/RHEL
sudo mkdir -p /mnt/nas
sudo mount -t nfs NAS_IP:/share /mnt/nas
#for example sudo mount -t nfs 192.168.1.100:/mnt/nas_share /mnt/nas
sudo mkdir -p /mnt/nas
sudo mount -t cifs -o username=login,password=passwd //NAS_IP/share /mnt/nas
mount with fstab, If you need
sudo nano /etc/fstab
NAS_IP:/share  /mnt/nas  nfs  defaults  0  0
sudo mount -a
Give full permissions and create the folders media_files, then specify them in Docker settings.
sudo mkdir -p /media_files  
sudo chmod -R 777 /media_files  # Full read/write/execute for all users (adjust permissions if needed)
sudo chown -R $USER:$USER /media_files  # Set ownership to your user

DOCKER:
-mnt/nas/media_files:/home/mediacms.io/mediacms/media_files/

**Comment by nigel-daniels** [comment]
Hi @gimail you mentioned adding a mount in a Linux environment but I'm not clear if you are suggesting these changes in the docker container running Linux or a host environment? 

I'm working on a MacOS host where `/Volumes/media` is the mount point for my NAS drive and has the following permissions `700` (on the host) with the same user and group ownership. From then on the permissions are `777`(within the mount on the NAS) with the same ownership. Or are you suggesting this is a mount point that is required in the container running Linux? The docker image I'm using is provided by `mediacms` so I want to avoid a situation where I change that.

**Comment by gimail** [comment]
Your path is not defined NAS in Linux: cd /mnt and then run the ls command.
sudo apt update && sudo apt install nfs-common cifs-utils -y  # Debian/Ubuntu
sudo dnf install nfs-utils cifs-utils -y     # Fedora/RHEL
sudo mkdir -p /mnt/nas
sudo mount -t nfs NAS_IP:/share /mnt/nas
#for example sudo mount -t nfs 192.168.1.100:/mnt/nas_share /mnt/nas
sudo mkdir -p /mnt/nas
sudo mount -t cifs -o username=login,password=passwd //NAS_IP/share /mnt/nas
mount with fstab, If you need
sudo nano /etc/fstab
NAS_IP:/share  /mnt/nas  nfs  defaults  0  0
sudo mount -a
Give full permissions and create the folders media_files, then specify them in Docker settings.
sudo mkdir -p /media_files  
sudo chmod -R 777 /media_files  # Full read/write/execute for all users (adjust permissions if needed)
sudo chown -R $USER:$USER /media_files  # Set ownership to your user

DOCKER:
-mnt/nas/media_files:/home/mediacms.io/mediacms/media_files/
 version: "3"

services:
  migrations:
    image: mediacms/mediacms:latest
    volumes:
      - ./deploy/docker/local_settings.py:/home/mediacms.io/mediacms/deploy/docker/local_settings.py
    environment:
      ENABLE_UWSGI: 'no'
      ENABLE_NGINX: 'no'
      ENABLE_CELERY_SHORT: 'no'
      ENABLE_CELERY_LONG: 'no'
      ENABLE_CELERY_BEAT: 'no'
      ADMIN_USER: 'admin'
      ADMIN_EMAIL: 'admin@localhost'
      #ADMIN_PASSWORD: 'uncomment_and_set_password_here'
    command: "./deploy/docker/prestart.sh"
    restart: on-failure
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
  web:
    image: mediacms/mediacms:latest
    deploy:
      replicas: 1
    ports:
      - "80:80"
    volumes:
      - media_store:/home/mediacms.io/mediacms/media_files/
      - static_store:/home/mediacms.io/mediacms/static/
      - ./deploy/docker/local_settings.py:/home/mediacms.io/mediacms/deploy/docker/local_settings.py
    environment:
      ENABLE_CELERY_BEAT: 'no'
      ENABLE_CELERY_SHORT: 'no'
      ENABLE_CELERY_LONG: 'no'
      ENABLE_MIGRATIONS: 'no'
    depends_on:
      - migrations
  celery_beat:
    image: mediacms/mediacms:latest
    volumes:
      - ./deploy/docker/local_settings.py:/home/mediacms.io/mediacms/deploy/docker/local_settings.py
    environment:
      ENABLE_UWSGI: 'no'
      ENABLE_NGINX: 'no'
      ENABLE_CELERY_SHORT: 'no'
      ENABLE_CELERY_LONG: 'no'
      ENABLE_MIGRATIONS: 'no'
    depends_on:
      - redis
  celery_worker:
    image: mediacms/mediacms:latest
    deploy:
      replicas: 1
    volumes:
      - media_store:/home/mediacms.io/mediacms/media_files/
      - static_store:/home/mediacms.io/mediacms/static/
      - ./deploy/docker/local_settings.py:/home/mediacms.io/mediacms/deploy/docker/local_settings.py
    environment:
      ENABLE_UWSGI: 'no'
      ENABLE_NGINX: 'no'
      ENABLE_CELERY_BEAT: 'no'
      ENABLE_MIGRATIONS: 'no'
    depends_on:
      - migrations
  db:
    image: postgres:17.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    environment:
      POSTGRES_USER: mediacms
      POSTGRES_PASSWORD: mediacms
      POSTGRES_DB: mediacms
      TZ: Europe/London
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}", "--host=db", "--dbname=$POSTGRES_DB", "--username=$POSTGRES_USER"]
      interval: 30s
      timeout: 10s
      retries: 5
  redis:
    image: "redis:alpine"
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 30s
      timeout: 10s
      retries: 3
volumes:
  postgres_data:
  media_store:
  static_store:

**Comment by gimail** [comment]
While I'm not an expert on macOS, probably...
Here's how to modify your Docker Compose file to connect the MediaCMS media_store to your NAS in macOS:

Modified docker-compose.yml

yaml

 

version: "3" services: volumes: # Replace media_store volume with NAS mount # Add these instead of the media_store volume: media_store: driver: local driver_opts: type: cifs o: username=your_nas_username,password=your_nas_password,uid=1000,gid=1000,file_mode=0770,dir_mode=0770 device: "//NAS_IP/media_files" 

Key Changes Made:

Removed the default media_store: volume definition

Added direct NAS connection via:

SMB/CIFS (recommended for macOS) or

NFS (if your NAS supports it)

Required Adjustments:

Replace these values:

your_nas_username - NAS login username

your_nas_password - NAS login password

NAS_IP - Your NAS IP address (e.g., 192.168.1.100)

/media_files - Your NAS share name

For macOS specifically:

Ensure the NAS share is mounted first (via Finder → Cmd+K → smb://NAS_IP/media_files)

Add the mount path to Docker Desktop:

Docker → Preferences → Resources → File Sharing

Add /Volumes/media_files (or your mount point)

Permission tips:

bash

 

chmod -R 770 /volume/media_files chown -R 1000:1000 /volume/media_files

**Comment by nigel-daniels** [comment]
I tried various versions of using volumes but I still cannot get it to work for me, I keep getting the error:
```
Error response from daemon: failed to populate volume: error while mounting volume '/var/lib/docker/volumes/mediacms_postgres_data/_data': error resolving passed in network volume address: lookup nas_host._smb._tcp.local on 192.168.65.7:53: read udp 192.168.65.6:63772->192.168.65.7:53: i/o timeout
```
It looks like it's trying to access an internal docker network so I have added the `extra_hosts` directive:
```
extra_hosts:
      - "host.docker.internal:host-gateway"
```
This should allow the containers to see the host network and reach the SMB share on the NAS. However I still get the same error. This is the full `docker-compose.yaml` I have tried using:

```
version: "3"

services:
  migrations:
    image: mediacms/mediacms:latest
    volumes:
      - ./deploy/docker/local_settings.py:/home/mediacms.io/mediacms/deploy/docker/local_settings.py
    environment:
      ENABLE_UWSGI: 'no'
      ENABLE_NGINX: 'no'
      ENABLE_CELERY_SHORT: 'no'
      ENABLE_CELERY_LONG: 'no'
      ENABLE_CELERY_BEAT: 'no'
      ADMIN_USER: 'admin'
      ADMIN_EMAIL: 'admin@localhost'
      ADMIN_PASSWORD: '********'
    command: "./deploy/docker/prestart.sh"
    restart: on-failure
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
  web:
    image: mediacms/mediacms:latest
    deploy:
      replicas: 1
    ports:
      - "80:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - media_store:/home/mediacms.io/mediacms/media_files/
      - static_store:/home/mediacms.io/mediacms/static/
      - ./deploy/docker/local_settings.py:/home/mediacms.io/mediacms/deploy/docker/local_settings.py
    environment:
      ENABLE_CELERY_BEAT: 'no'
      ENABLE_CELERY_SHORT: 'no'
      ENABLE_CELERY_LONG: 'no'
      ENABLE_MIGRATIONS: 'no'
    depends_on:
      - migrations
  celery_beat:
    image: mediacms/mediacms:latest
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./deploy/docker/local_settings.py:/home/mediacms.io/mediacms/deploy/docker/local_settings.py
    environment:
      ENABLE_UWSGI: 'no'
      ENABLE_NGINX: 'no'
      ENABLE_CELERY_SHORT: 'no'
      ENABLE_CELERY_LONG: 'no'
      ENABLE_MIGRATIONS: 'no'
    depends_on:
      - redis
  celery_worker:
    image: mediacms/mediacms:latest
    deploy:
      replicas: 1
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - media_store:/home/mediacms.io/mediacms/media_files/
      - static_store:/home/mediacms.io/mediacms/static/
      - ./deploy/docker/local_settings.py:/home/mediacms.io/mediacms/deploy/docker/local_settings.py
    environment:
      ENABLE_UWSGI: 'no'
      ENABLE_NGINX: 'no'
      ENABLE_CELERY_BEAT: 'no'
      ENABLE_MIGRATIONS: 'no'
    depends_on:
      - migrations
  db:
    image: postgres:17.2-alpine
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    environment:
      POSTGRES_USER: mediacms
      POSTGRES_PASSWORD: mediacms
      POSTGRES_DB: mediacms
      TZ: US/Pacific
    healthcheck:
      test: ["CMD-SHELL",  "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}", "--host=db", "--dbname=$POSTGRES_DB", "--username=$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: "redis:alpine"
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 30s
      timeout: 10s
      retries: 3
volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: "cifs"
      o: "username=user_name,password=********,uid=501,gid=20,file_mode=0770,dir_mode=0770"
      device: "smb://nas_host._smb._tcp.local/media/postgres_data/"
  media_store:
    driver: local
    driver_opts:
      type: "cifs"
      o: "username= user_name,password=********,uid=501,gid=20,file_mode=0770,dir_mode=0770"
      device: "smb://nas_host._smb._tcp.local/media/media_files/"
  static_store:
    driver: local
    driver_opts:
      type: "cifs"
      o: "username= user_name,password=********,uid=501,gid=20,file_mode=0770,dir_mode=0770"
      device: "smb://nas_host._smb._tcp.local/media/static_store/"
```

**Comment by gimail** [comment]
nas_host._smb._tcp.local but does not work from inside containers
1.Use IP address instead of .local name
    device: "//192.168.1.100/media/postgres_data"
    device: "//192.168.1.100/media/media_files"
    device: "//192.168.1.100/media/static_store"
2. Write static DNS in /etc/hosts
    sudo nano /etc/hosts
    192.168.1.100 nas_host

**Comment by nigel-daniels** [comment]
I tried using the ip address of the NAS in place of the host name:
```
postgres_data:
    driver: local
    driver_opts:
      type: "cifs"
      o: "username=user_name,password=********,uid=501,gid=20,file_mode=0770,dir_mode=0770"
      device: "smb://10.0.0.100/media/postgres_data/"
```
but now I get an invalid argument error. I tried with and without the `extra_hosts` but I just get the same result:
```
Error response from daemon: failed to populate volume: error while mounting volume '/var/lib/docker/volumes/mediacms_postgres_data/_data': failed to mount local volume: mount smb://10.0.0.100/media/postgres_data/:/var/lib/docker/volumes/mediacms_postgres_data/_data, data: username=user_name,password=********,uid=501,gid=20,file_mode=0770,dir_mode=0770: invalid argument 
```
As far as I can tell the `o:` directives are correct and the `uid` & `gid` match the user name supplied. I can connect directly to the host using finders Connect to Server option so URL in the `device:` section is ok.
