### ISSUE TITLE
Docker installation failed at postgres_data and 502 afterwards

### ISSUE THREAD

**Issue by rajanverma-me** [mediacms-io/mediacms#286]
After running `docker-compose up` at the end it got failed with 
```
Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /Users/rajan/workspace/postgres_data  
````
I am still trying to find where the postgres_data is .. there is no documentation, also no updates about this folder. why is it showing outside of root directory in docker-compose.yaml

````
db:
    image: postgres
    volumes:
      - ../postgres_data:/var/lib/postgresql/data/
````
but inside the root directory in gitignore 

````
...
media_files/chunks/
media_files/uploads/
postgres_data/
celerybeat-schedule
logs/
pids
...
````

and again outside the root directory in docker-compose-dev

````
  db:
    image: postgres
    volumes:
      - ../postgres_data:/var/lib/postgresql/data/
````

again inside the root directory in. docker-compose-named-volumes.yaml

````
db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
````

Moreover, I manually created it and got it worked but 
HTTP://localhost is still not accesssible. It says 502 Bad gateway.
Some logs when I hit the localhost:

````
web_1            | invalid request block size: 8714 (max 4096)...skip
web_1            | 2021/08/26 04:13:20 [error] 149#149: *1 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 172.19.0.1, server: , request: "GET / HTTP/1.1", upstream: "uwsgi://127.0.0.1:9000", host: "localhost"
web_1            | 172.19.0.1 - - [26/Aug/2021:04:13:20 +0000] "GET / HTTP/1.1" 502 575 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36"
web_1            | Thu Aug 26 05:13:21 2021 - *** uWSGI listen queue of socket "127.0.0.1:9000" (fd: 3) full !!! (26518415/64) ***
web_1            | invalid request block size: 8641 (max 4096)...skip
web_1            | 172.19.0.1 - - [26/Aug/2021:04:13:21 +0000] "GET /favicon.ico HTTP/1.1" 502 575 "http://localhost/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36"
web_1            | 2021/08/26 04:13:21 [error] 149#149: *1 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 172.19.0.1, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "uwsgi://127.0.0.1:9000", host: "localhost", referrer: "http://localhost/"
````

Please guide. 

I am using MacOS BigSur  V: 11.4 (20F71)
