### ISSUE TITLE
15+ min startup time for MediaCMS

### ISSUE THREAD

**Issue by xDvck** [mediacms-io/mediacms#410]
Description:
I installed MediaCMS on a VM and it takes more than 15 minutes for it to start via docker-compose.
The service starts up normally until a certain point, then stops for about 15 minutes and then continues to start up.
While the containers seem "stuck" in their process the webpage reports "Error 502"

Logs (until the service gets stuck, after that i assume the services start normally):
```Attaching to mediacms_web_1, mediacms_celery_worker_2, mediacms_celery_worker_1, mediacms_migrations_1, mediacms_celery_beat_1, mediacms_nginx-proxy_1, mediacms_redis_1, mediacms_db_1
 [35mdb_1             | [0m 
 [35mdb_1             | [0m PostgreSQL Database directory appears to contain a database; Skipping initialization
 [35mdb_1             | [0m 
 [35mdb_1             | [0m 2022-02-03 15:45:28.114 UTC [1] LOG:  starting PostgreSQL 13.5 (Debian 13.5-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
 [35mdb_1             | [0m 2022-02-03 15:45:28.114 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
 [35mdb_1             | [0m 2022-02-03 15:45:28.115 UTC [1] LOG:  listening on IPv6 address "::", port 5432
 [35mdb_1             | [0m 2022-02-03 15:45:28.279 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
 [35mdb_1             | [0m 2022-02-03 15:45:28.729 UTC [27] LOG:  database system was shut down at 2022-02-03 15:45:11 UTC
 [35mdb_1             | [0m 2022-02-03 15:45:28.816 UTC [1] LOG:  database system is ready to accept connections
 [36;1mnginx-proxy_1    | [0m Info: running nginx-proxy version 0.10.0-11-g42c8b0c
 [36;1mnginx-proxy_1    | [0m Warning: A custom dhparam.pem file was provided. Best practice is to use standardized RFC7919 DHE groups instead.
 [36;1mnginx-proxy_1    | [0m  [0;37;1mforego      |  [0mstarting dockergen.1 on port 5000
 [36;1mnginx-proxy_1    | [0m  [0;37;1mforego      |  [0mstarting nginx.1 on port 5100
 [36;1mnginx-proxy_1    | [0m  [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:45:28 [notice] 19#19: using the "epoll" event method
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:45:28 [notice] 19#19: nginx/1.21.5
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:45:28 [notice] 19#19: built by gcc 10.2.1 20210110 (Debian 10.2.1-6) 
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:45:28 [notice] 19#19: OS: Linux 5.4.0-97-generic
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:45:28 [notice] 19#19: getrlimit(RLIMIT_NOFILE): 1048576:1048576
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:45:28 [notice] 19#19: start worker processes
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:45:28 [notice] 19#19: start worker process 24
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:45:28 [notice] 19#19: start worker process 25
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:45:28 [notice] 19#19: start worker process 26
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:45:28 [notice] 19#19: start worker process 27
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:45:28 [notice] 19#19: start worker process 28
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:45:28 [notice] 19#19: start worker process 29
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:45:28 [notice] 19#19: start worker process 30
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:45:28 [notice] 19#19: start worker process 31
 [36;1mnginx-proxy_1    | [0m  [0m [0;36;1mdockergen.1 |  [0;31;1m2022/02/03 15:45:28 Generated '/etc/nginx/conf.d/default.conf' from 3 containers
 [36;1mnginx-proxy_1    | [0m  [0m [0;36;1mdockergen.1 |  [0;31;1m2022/02/03 15:45:28 Running 'nginx -s reload'
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:45:28 [notice] 19#19: signal 1 (SIGHUP) received from 33, reconfiguring
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:45:28 [notice] 19#19: reconfiguring
 [36;1mnginx-proxy_1    | [0m  [0m [0;36;1mdockergen.1 |  [0;31;1m2022/02/03 15:45:28 Watching docker events
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:45:28 [notice] 19#19: using the "epoll" event method
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:45:28 [notice] 19#19: start worker processes
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:45:28 [notice] 19#19: start worker process 37
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:45:28 [notice] 19#19: start worker process 38
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:45:28 [notice] 19#19: start worker process 39
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:45:28 [notice] 19#19: start worker process 40
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:45:28 [notice] 19#19: start worker process 41
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:45:28 [notice] 19#19: start worker process 42
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:45:28 [notice] 19#19: start worker process 43
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:45:28 [notice] 19#19: start worker process 44
 [36;1mnginx-proxy_1    | [0m  [0m [0;36;1mdockergen.1 |  [0;31;1m2022/02/03 15:45:28 Error inspecting container: 78edf33ac27c39498096d3ff6f622db11cd7ac8639f1666ccf990aa86db6d035: No such container: 78edf33ac27c39498096d3ff6f622db11cd7ac8639f1666ccf990aa86db6d035
 [36;1mnginx-proxy_1    | [0m  [0m [0;36;1mdockergen.1 |  [0;31;1m2022/02/03 15:45:28 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification 'nginx -s reload'
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:45:28 [notice] 27#27: gracefully shutting down
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:45:28 [notice] 24#24: gracefully shutting down
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:45:28 [notice] 27#27: exiting
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:45:28 [notice] 24#24: exiting
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:45:28 [notice] 27#27: exit
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:45:28 [notice] 24#24: exit
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:45:28 [notice] 29#29: gracefully shutting down
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:45:28 [notice] 29#29: exiting
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:45:28 [notice] 25#25: gracefully shutting down
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:45:28 [notice] 25#25: exiting
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:45:28 [notice] 29#29: exit
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:45:28 [notice] 25#25: exit
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:45:28 [notice] 26#26: gracefully shutting down
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:45:28 [notice] 26#26: exiting
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:45:28 [notice] 31#31: gracefully shutting down
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:45:28 [notice] 31#31: exiting
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:45:28 [notice] 26#26: exit
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:45:28 [notice] 30#30: gracefully shutting down
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:45:28 [notice] 30#30: exiting
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:45:28 [notice] 31#31: exit
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:45:28 [notice] 28#28: gracefully shutting down
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:45:28 [notice] 30#30: exit
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:45:28 [notice] 28#28: exiting
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:45:28 [notice] 28#28: exit
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:45:28 [notice] 19#19: signal 17 (SIGCHLD) received from 27
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:45:28 [notice] 19#19: worker process 27 exited with code 0
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:45:28 [notice] 19#19: signal 29 (SIGIO) received
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:45:28 [notice] 19#19: signal 17 (SIGCHLD) received from 30
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:45:28 [notice] 19#19: worker process 30 exited with code 0
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:45:28 [notice] 19#19: signal 29 (SIGIO) received
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:45:28 [notice] 19#19: signal 17 (SIGCHLD) received from 28
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:45:28 [notice] 19#19: worker process 28 exited with code 0
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:45:28 [notice] 19#19: signal 29 (SIGIO) received
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:45:28 [notice] 19#19: signal 17 (SIGCHLD) received from 31
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:45:28 [notice] 19#19: worker process 31 exited with code 0
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:45:28 [notice] 19#19: signal 29 (SIGIO) received
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:45:28 [notice] 19#19: signal 17 (SIGCHLD) received from 26
 [33;1mredis_1          | [0m 1:C 03 Feb 2022 15:45:27.393 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
 [33;1mredis_1          | [0m 1:C 03 Feb 2022 15:45:27.393 # Redis version=6.2.6, bits=64, commit=00000000, modified=0, pid=1, just started
 [33;1mredis_1          | [0m 1:C 03 Feb 2022 15:45:27.393 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
 [33;1mredis_1          | [0m 1:M 03 Feb 2022 15:45:27.396 * monotonic clock: POSIX clock_gettime
 [33;1mredis_1          | [0m 1:M 03 Feb 2022 15:45:27.402 * Running mode=standalone, port=6379.
 [33;1mredis_1          | [0m 1:M 03 Feb 2022 15:45:27.403 # Server initialized
 [33;1mredis_1          | [0m 1:M 03 Feb 2022 15:45:27.404 * Loading RDB produced by version 6.2.6
 [33;1mredis_1          | [0m 1:M 03 Feb 2022 15:45:27.404 * RDB age 10 seconds
 [33;1mredis_1          | [0m 1:M 03 Feb 2022 15:45:27.404 * RDB memory usage when created 0.78 Mb
 [33;1mredis_1          | [0m 1:M 03 Feb 2022 15:45:27.404 # Done loading RDB, keys loaded: 4, keys expired: 0.
 [33;1mredis_1          | [0m 1:M 03 Feb 2022 15:45:27.404 * DB loaded from disk: 0.000 seconds
 [33;1mredis_1          | [0m 1:M 03 Feb 2022 15:45:27.404 * Ready to accept connections
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:45:28 [notice] 19#19: worker process 26 exited with code 0
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:45:28 [notice] 19#19: signal 29 (SIGIO) received
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:45:28 [notice] 19#19: signal 17 (SIGCHLD) received from 29
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:45:28 [notice] 19#19: worker process 29 exited with code 0
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:45:28 [notice] 19#19: signal 29 (SIGIO) received
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:45:28 [notice] 19#19: signal 17 (SIGCHLD) received from 25
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:45:28 [notice] 19#19: worker process 25 exited with code 0
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:45:28 [notice] 19#19: signal 29 (SIGIO) received
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:45:28 [notice] 19#19: signal 17 (SIGCHLD) received from 24
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:45:28 [notice] 19#19: worker process 24 exited with code 0
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:45:28 [notice] 19#19: signal 29 (SIGIO) received
 [36;1mnginx-proxy_1    | [0m  [0m [0;36;1mdockergen.1 |  [0;31;1m2022/02/03 15:45:30 Received event start for container 78edf33ac27c
 [36;1mnginx-proxy_1    | [0m  [0m [0;36;1mdockergen.1 |  [0;31;1m2022/02/03 15:45:30 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification 'nginx -s reload'
 [36;1mnginx-proxy_1    | [0m  [0m [0;36;1mdockergen.1 |  [0;31;1m2022/02/03 15:46:01 Received event start for container 4b87919c901f
 [36;1mnginx-proxy_1    | [0m  [0m [0;36;1mdockergen.1 |  [0;31;1m2022/02/03 15:46:01 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification 'nginx -s reload'
 [36;1mnginx-proxy_1    | [0m  [0m [0;36;1mdockergen.1 |  [0;31;1m2022/02/03 15:46:11 Received event start for container 72069d3c34b3
 [36;1mnginx-proxy_1    | [0m  [0m [0;36;1mdockergen.1 |  [0;31;1m2022/02/03 15:46:11 Received event start for container 0cf80b8c87b9
 [36;1mnginx-proxy_1    | [0m  [0m [0;36;1mdockergen.1 |  [0;31;1m2022/02/03 15:46:11 Received event start for container c64ab6777234
 [36;1mnginx-proxy_1    | [0m  [0m [0;36;1mdockergen.1 |  [0;31;1m2022/02/03 15:46:12 Generated '/etc/nginx/conf.d/default.conf' from 8 containers
 [36;1mnginx-proxy_1    | [0m  [0m [0;36;1mdockergen.1 |  [0;31;1m2022/02/03 15:46:12 Running 'nginx -s reload'
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:46:12 [notice] 19#19: signal 1 (SIGHUP) received from 48, reconfiguring
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:46:12 [notice] 19#19: reconfiguring
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:46:12 [notice] 19#19: using the "epoll" event method
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:46:12 [notice] 19#19: start worker processes
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:46:12 [notice] 19#19: start worker process 49
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:46:12 [notice] 19#19: start worker process 50
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:46:12 [notice] 19#19: start worker process 51
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:46:12 [notice] 19#19: start worker process 52
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:46:12 [notice] 19#19: start worker process 53
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:46:12 [notice] 19#19: start worker process 54
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:46:12 [notice] 19#19: start worker process 55
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:46:12 [notice] 19#19: start worker process 56
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:46:12 [notice] 37#37: gracefully shutting down
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:46:12 [notice] 38#38: gracefully shutting down
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:46:12 [notice] 37#37: exiting
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:46:12 [notice] 38#38: exiting
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:46:12 [notice] 37#37: exit
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:46:12 [notice] 38#38: exit
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:46:12 [notice] 39#39: gracefully shutting down
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:46:12 [notice] 39#39: exiting
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:46:12 [notice] 39#39: exit
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:46:12 [notice] 40#40: gracefully shutting down
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:46:12 [notice] 40#40: exiting
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:46:12 [notice] 40#40: exit
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:46:12 [notice] 41#41: gracefully shutting down
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:46:12 [notice] 41#41: exiting
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:46:12 [notice] 41#41: exit
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:46:12 [notice] 42#42: gracefully shutting down
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:46:12 [notice] 42#42: exiting
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:46:12 [notice] 42#42: exit
 [36;1mnginx-proxy_1    | [0m  [0m [0;36;1mdockergen.1 |  [0;31;1m2022/02/03 15:46:12 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification 'nginx -s reload'
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:46:12 [notice] 43#43: gracefully shutting down
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:46:12 [notice] 43#43: exiting
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:46:12 [notice] 43#43: exit
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:46:12 [notice] 44#44: gracefully shutting down
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:46:12 [notice] 44#44: exiting
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:46:12 [notice] 44#44: exit
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:46:12 [notice] 19#19: signal 17 (SIGCHLD) received from 39
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:46:12 [notice] 19#19: worker process 39 exited with code 0
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:46:12 [notice] 19#19: signal 29 (SIGIO) received
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:46:12 [notice] 19#19: signal 17 (SIGCHLD) received from 38
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:46:12 [notice] 19#19: worker process 38 exited with code 0
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:46:12 [notice] 19#19: signal 29 (SIGIO) received
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:46:12 [notice] 19#19: signal 17 (SIGCHLD) received from 37
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:46:12 [notice] 19#19: worker process 37 exited with code 0
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:46:12 [notice] 19#19: signal 29 (SIGIO) received
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:46:12 [notice] 19#19: signal 17 (SIGCHLD) received from 44
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:46:12 [notice] 19#19: worker process 43 exited with code 0
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:46:12 [notice] 19#19: worker process 44 exited with code 0
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:46:12 [notice] 19#19: worker process 41 exited with code 0
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:46:12 [notice] 19#19: signal 29 (SIGIO) received
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:46:12 [notice] 19#19: signal 17 (SIGCHLD) received from 43
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:46:12 [notice] 19#19: worker process 42 exited with code 0
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:46:12 [notice] 19#19: signal 29 (SIGIO) received
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:46:12 [notice] 19#19: signal 17 (SIGCHLD) received from 42
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:46:12 [notice] 19#19: signal 17 (SIGCHLD) received from 40
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:46:12 [notice] 19#19: worker process 40 exited with code 0
 [36;1mnginx-proxy_1    | [0m  [0m [0;33;1mnginx.1     |  [0;31;1m2022/02/03 15:46:12 [notice] 19#19: signal 29 (SIGIO) received
 [36;1mnginx-proxy_1    | [0m  [0m [0;36;1mdockergen.1 |  [0;31;1m2022/02/03 15:46:12 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification 'nginx -s reload'
```

Reproduction:
I don't know how to exactly reproduce this issue other than using the exact setup I have

**Environment (please complete the following information):**
Added an NGINX-Proxy for SSL, since the Server runs in an Intranet -> not accessible by Let's Encrypt
The machine is running Ubuntu-Server 20.04 LTS, has 8 cores and 8 GB of RAM. None of those two is significantly loaded during startup.

**Comment by xDvck** [comment]
Also it looks like MediaCMS uses more RAM every time I boot it up. It started somewhere around using 4GB, now it's over 5GB.

**Comment by xDvck** [comment]
Upon further investigation, I think the issue is related to the NGINX-Proxy-Container

**Comment by mgogoulos** [comment]
Hi @xDvck , this seems to be related to the changes on docker-compose file, can you show us what compose file you're using and if you did any change?

**Comment by xDvck** [comment]
```
version: "3"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./deploy/docker/reverse_proxy/certs/:/etc/nginx/certs/
      - ./deploy/docker/reverse_proxy/client_max_body_size.conf:/etc/nginx/conf.d/client_max_body_size.conf:ro
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
  migrations:
    image: mediacms/mediacms:latest
    restart: always
    volumes:
      - ./:/home/mediacms.io/mediacms/
    environment:
      ENABLE_UWSGI: 'yes'
      ENABLE_NGINX: 'yes'
      ENABLE_CELERY_SHORT: 'yes'
      ENABLE_CELERY_LONG: 'yes'
      ENABLE_CELERY_BEAT: 'yes'
    command: "./deploy/docker/prestart.sh"
    restart: on-failure
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
  web:
    image: mediacms/mediacms:latest
    restart: always
    deploy:
      replicas: 1
    volumes:
      - ./:/home/mediacms.io/mediacms/
    environment:
      ENABLE_CELERY_BEAT: 'yes'
      ENABLE_CELERY_SHORT: 'yes'
      ENABLE_CELERY_LONG: 'yes'
      ENABLE_MIGRATIONS: 'yes'
      ADMIN_USER: 'admin'
      ADMIN_EMAIL: 'admin@localhost'
      #ADMIN_PASSWORD: [pw]'
      VIRTUAL_HOST: '[domain.name]'
    depends_on:
      - migrations
  celery_beat:
    image: mediacms/mediacms:latest
    restart: always
    volumes:
      - ./:/home/mediacms.io/mediacms/
    environment:
      ENABLE_UWSGI: 'yes'
      ENABLE_NGINX: 'yes'
      ENABLE_CELERY_SHORT: 'yes'
      ENABLE_CELERY_LONG: 'yes'
      ENABLE_MIGRATIONS: 'yes'
    depends_on:
      - redis
  celery_worker:
    image: mediacms/mediacms:latest
    restart: always
    deploy:
      replicas: 2
    volumes:
      - ./:/home/mediacms.io/mediacms/
    environment:
      ENABLE_UWSGI: 'yes'
      ENABLE_NGINX: 'yes'
      ENABLE_CELERY_BEAT: 'yes'
      ENABLE_MIGRATIONS: 'yes'
    depends_on:
      - migrations
  db:
    image: postgres:13
    restart: always
    volumes:
      - ../postgres_data/:/var/lib/postgresql/data/
    restart: always
    environment:
      POSTGRES_USER: mediacms
      POSTGRES_PASSWORD: mediacms
      POSTGRES_DB: mediacms
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mediacms"]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: "redis:alpine"
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 30s
      timeout: 10s
      retries: 3
volumes:
  conf:
  vhost:
  html:
  dhparam:
```
