### ISSUE TITLE
ffprobe outputs an invalid integer in some cases

### ISSUE THREAD

**Issue by tschig** [mediacms-io/mediacms#417]
**Describe the issue**
I am trying to upload video.mkv File with ~200mb.
When I Upload it via "https://mediacms.exmaple.com/upload" the fineupload "?done" request fails with Status Code 400 and Response:
```
Request URL: https://mediacms.exmaple.com/fu/upload/?done
Request Method: POST
Status Code: 400
{"success": false, "error": "Error with File Uploading"}
```

On the server, the file video.mkv is present and does have the same md5 as the file on my local harddrive.

Server:
```bash
root@d0dd55e3af29:/home/mediacms.io/mediacms/media_files/uploads/1f2ca7a0-167b-42a8-9a43-84a54e85b406# pwd
/home/mediacms.io/mediacms/media_files/uploads/1f2ca7a0-167b-42a8-9a43-84a54e85b406
root@d0dd55e3af29:/home/mediacms.io/mediacms/media_files/uploads/1f2ca7a0-167b-42a8-9a43-84a54e85b406# ls -al
total 204236
drwxr-xr-x 2 www-data www-data       4096 Feb 19 10:49 .
drwxr-xr-x 9 www-data tempgroup      4096 Feb 19 10:40 ..
-rw-r--r-- 1 www-data www-data  209126313 Feb 19 10:40 video.mkv
-rw-r--r-- 1 www-data www-data          0 Feb 19 10:49 video_8pZlTQB.mkv
-rw-r--r-- 1 www-data www-data          0 Feb 19 10:41 video_aqUqPbb.mkv
-rw-r--r-- 1 www-data www-data          0 Feb 19 10:41 video_oLhah4M.mkv
root@d0dd55e3af29:/home/mediacms.io/mediacms/media_files/uploads/1f2ca7a0-167b-42a8-9a43-84a54e85b406# md5sum video.mkv
0a1dcb25b162786b87826b95be394584  video.mkv
```

Local:
```
C:\Users\justi>md5sum video.mkv
0a1dcb25b162786b87826b95be394584 *video.mkv
```

So upload was correct. 
When trying the same with a smaller video file, everything works.
When trying the same file with a Single Server installation in a VM everything works

Log from Docker Container "web":
```

[pid: 61|app: 0|req: 125/442] 172.25.0.8 () {76 vars in 1671 bytes} [Sat Feb 19 10:40:58 2022] POST /fu/upload/ => generated 17 bytes in 15 msecs (HTTP/1.1 200) 6 headers in 175 bytes (1 switches on core 0)
172.25.0.8 - - [19/Feb/2022:10:40:58 +0000] "POST /fu/upload/ HTTP/1.1" 200 17 "https://mediacms.example.com/upload" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36"
2022/02/19 10:40:58 [warn] 58#58: *358 a client request body is buffered to a temporary file /var/lib/nginx/body/0000000419, client: 172.25.0.8, server: , request: "POST /fu/upload/ HTTP/1.1", host: "mediacms.example.com", referrer: "https://mediacms.example.com/upload"
[pid: 63|app: 0|req: 318/443] 172.25.0.8 () {76 vars in 1671 bytes} [Sat Feb 19 10:40:58 2022] POST /fu/upload/ => generated 17 bytes in 15 msecs (HTTP/1.1 200) 6 headers in 175 bytes (2 switches on core 1)
172.25.0.8 - - [19/Feb/2022:10:40:58 +0000] "POST /fu/upload/ HTTP/1.1" 200 17 "https://mediacms.example.com/upload" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36"
[pid: 63|app: 0|req: 319/444] 172.25.0.8 () {76 vars in 1671 bytes} [Sat Feb 19 10:40:58 2022] POST /fu/upload/ => generated 17 bytes in 15 msecs (HTTP/1.1 200) 6 headers in 175 bytes (1 switches on core 0)
172.25.0.8 - - [19/Feb/2022:10:40:58 +0000] "POST /fu/upload/ HTTP/1.1" 200 17 "https://mediacms.example.com/upload" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36"
2022/02/19 10:40:58 [warn] 58#58: *357 a client request body is buffered to a temporary file /var/lib/nginx/body/0000000420, client: 172.25.0.8, server: , request: "POST /fu/upload/ HTTP/1.1", host: "mediacms.example.com", referrer: "https://mediacms.example.com/upload"
[pid: 61|app: 0|req: 126/445] 172.25.0.8 () {76 vars in 1671 bytes} [Sat Feb 19 10:40:58 2022] POST /fu/upload/ => generated 17 bytes in 15 msecs (HTTP/1.1 200) 6 headers in 175 bytes (1 switches on core 1)
172.25.0.8 - - [19/Feb/2022:10:40:58 +0000] "POST /fu/upload/ HTTP/1.1" 200 17 "https://mediacms.example.com/upload" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36"
[pid: 63|app: 0|req: 320/446] 172.25.0.8 () {76 vars in 1671 bytes} [Sat Feb 19 10:40:58 2022] POST /fu/upload/ => generated 17 bytes in 13 msecs (HTTP/1.1 200) 6 headers in 175 bytes (1 switches on core 1)
172.25.0.8 - - [19/Feb/2022:10:40:58 +0000] "POST /fu/upload/ HTTP/1.1" 200 17 "https://mediacms.example.com/upload" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36"
[pid: 63|app: 0|req: 321/447] 172.25.0.8 () {72 vars in 1533 bytes} [Sat Feb 19 10:40:59 2022] POST /fu/upload/?done => generated 21654 bytes in 2245 msecs (HTTP/1.1 500) 6 headers in 206 bytes (1 switches on core 0)
172.25.0.8 - - [19/Feb/2022:10:41:01 +0000] "POST /fu/upload/?done HTTP/1.1" 500 21654 "https://mediacms.example.com/upload" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36"
[pid: 63|app: 0|req: 322/448] 172.25.0.8 () {72 vars in 1533 bytes} [Sat Feb 19 10:41:06 2022] POST /fu/upload/?done => generated 56 bytes in 9 msecs (HTTP/1.1 400) 6 headers in 184 bytes (1 switches on core 1)
172.25.0.8 - - [19/Feb/2022:10:41:06 +0000] "POST /fu/upload/?done HTTP/1.1" 400 56 "https://mediacms.example.com/upload" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36"
[pid: 63|app: 0|req: 323/449] 172.25.0.8 () {72 vars in 1533 bytes} [Sat Feb 19 10:41:11 2022] POST /fu/upload/?done => generated 56 bytes in 8 msecs (HTTP/1.1 400) 6 headers in 184 bytes (1 switches on core 0)
172.25.0.8 - - [19/Feb/2022:10:41:11 +0000] "POST /fu/upload/?done HTTP/1.1" 400 56 "https://mediacms.example.com/upload" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36"
[pid: 63|app: 0|req: 324/450] 172.25.0.8 () {72 vars in 1533 bytes} [Sat Feb 19 10:49:01 2022] POST /fu/upload/?done => generated 56 bytes in 10 msecs (HTTP/1.1 400) 6 headers in 184 bytes (1 switches on core 1)
172.25.0.8 - - [19/Feb/2022:10:49:01 +0000] "POST /fu/upload/?done HTTP/1.1" 400 56 "https://mediacms.example.com/upload" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36"
[pid: 63|app: 0|req: 325/451] 172.25.0.8 () {66 vars in 1415 bytes} [Sat Feb 19 10:49:56 2022] GET /fu/upload/?done => generated 0 bytes in 7 msecs (HTTP/1.1 405) 7 headers in 211 bytes (1 switches on core 0)
172.25.0.8 - - [19/Feb/2022:10:49:56 +0000] "GET /fu/upload/?done HTTP/1.1" 405 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36"
```

**To Reproduce**
Steps to reproduce the issue:
1. Setup MediaCMS via Docker-Compose installation
2. Upload File
3. See error on GUI

**Expected behavior**
Upload works.

**Screenshots**
![image](https://user-images.githubusercontent.com/1055580/154798174-4d1cf53d-4cb9-4e39-bf26-549bac66c881.png)

**Environment (please complete the following information):**
 - OS: Ubuntu on Host
 - Installation method: Docker-Compose

docker-compose.yml
```
version: "3"

services:
  mediacms_migrations:
    image: mediacms/mediacms:latest
    volumes:
      - ./mediacms/:/home/mediacms.io/mediacms/
    environment:
      ENABLE_UWSGI: 'no'
      ENABLE_NGINX: 'no'
      ENABLE_CELERY_SHORT: 'no'
      ENABLE_CELERY_LONG: 'no'
      ENABLE_CELERY_BEAT: 'no'
      ADMIN_USER: 'admin'
      ADMIN_EMAIL: 'admin@localhost'
      #ADMIN_PASSWORD: 'uncomment_and_set_password_here'
    command: "./deploy/docker/prestart.sh"
    restart: on-failure
    depends_on:
      mediacms_redis:
        condition: service_healthy
      mediacms_db:
        condition: service_healthy
    networks:
      - proxy
  mediacms_web:
    image: mediacms/mediacms:latest
    restart: always
    deploy:
      replicas: 1
    ports:
      - 80
    volumes:
      - ./mediacms/:/home/mediacms.io/mediacms/
    environment:
      ENABLE_CELERY_BEAT: 'no'
      ENABLE_CELERY_SHORT: 'no'
      ENABLE_CELERY_LONG: 'no'
      ENABLE_MIGRATIONS: 'no'
    depends_on:
      - mediacms_migrations
    networks:
      - proxy
    labels:     
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.mediacms.rule=Host(`mediacms.example.com`)"
      - "traefik.http.routers.mediacms.entrypoints=https"
      - "traefik.http.routers.mediacms.service=mediacms"
      - "traefik.http.routers.mediacms.tls=true"
      - "traefik.http.services.mediacms.loadbalancer.server.port=80"
  celery_beat:
    image: mediacms/mediacms:latest
    restart: always
    volumes:
      - ./mediacms/:/home/mediacms.io/mediacms/
    environment:
      ENABLE_UWSGI: 'no'
      ENABLE_NGINX: 'no'
      ENABLE_CELERY_SHORT: 'no'
      ENABLE_CELERY_LONG: 'no'
      ENABLE_MIGRATIONS: 'no'
    depends_on:
      - mediacms_redis
    networks:
      - proxy
  celery_worker:
    image: mediacms/mediacms:latest
    restart: always
    deploy:
      replicas: 1
    volumes:
      - ./mediacms/:/home/mediacms.io/mediacms/
    environment:
      ENABLE_UWSGI: 'no'
      ENABLE_NGINX: 'no'
      ENABLE_CELERY_BEAT: 'no'
      ENABLE_MIGRATIONS: 'no'
    depends_on:
      - mediacms_migrations
    networks:
      - proxy
  mediacms_db:
    image: postgres:13
    volumes:
      - /srv/mediacms/postgres_data:/var/lib/postgresql/data/
    restart: always
    environment:
      POSTGRES_USER: mediacms
      POSTGRES_PASSWORD: mediacms
      POSTGRES_DB: mediacms
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mediacms"]
      interval: 10s
      timeout: 5s
      retries: 5
    #ports:
    #  - "5433:5432"
    networks:
      - proxy
  mediacms_redis:
    image: "redis:alpine"
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - proxy
networks:
  proxy:
    external: true
```

local_settings.py
```
FRONTEND_HOST = 'https://mediacms.example.com'
PORTAL_NAME = 'MediaCMS'
SECRET_KEY = 'xxx'
POSTGRES_HOST = 'mediacms_db'
REDIS_LOCATION = "redis://mediacms_redis:6379/1"

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "mediacms",
        "HOST": POSTGRES_HOST,
        "PORT": "5432",
        "USER": "mediacms",
        "PASSWORD": "mediacms",
    }
}

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": REDIS_LOCATION,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
    }
}

# CELERY STUFF
BROKER_URL = REDIS_LOCATION
CELERY_RESULT_BACKEND = BROKER_URL

MP4HLS_COMMAND = "/home/mediacms.io/bento4/bin/mp4hls"

DEBUG = True

# Flowside Config

REGISTER_ALLOWED = False
PORTAL_WORKFLOW = "private"
UPLOAD_MAX_SIZE = 800 * 1024 * 1000 * 5
```
