### ISSUE TITLE
Improve Documentation for productive docker environment

### ISSUE THREAD

**Issue by ykorzikowski** [mediacms-io/mediacms#709]
Hey there, 

it took me a while to understand the architecture of mediacms. The setup-guide was not working for me in the beginning. 

I had to set `ENABLE_UWSGI` to `yes`by uncommenting it. Otherwise I got a Bad Gateway from the nginx proxy. 

I also removed postgres as I use a productive database hosted on a different machine. 

for volumes, I only mount logs, media and the deploy-directory, as it contains configuration details. 

I would not recommend mount the whole git-repo, as you overwrite the containers code, which makes no sense IMHO.  

```
version: "3"

services:
  redis:
    image: "redis:alpine"
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  migrations:
    image: mediacms/mediacms:latest
    volumes:
      - /mnt/mediacms/deploy:/home/mediacms.io/mediacms/deploy
      - /mnt/mediacms/logs:/home/mediacms.io/mediacms/logs
      - /mnt/mediacms/media_files:/home/mediacms.io/mediacms/media_files
    environment:
      ENABLE_UWSGI: 'no'
      ENABLE_NGINX: 'no'
      ENABLE_CELERY_SHORT: 'no'
      ENABLE_CELERY_LONG: 'no'
      ENABLE_CELERY_BEAT: 'no'
      ADMIN_USER: 'admin'
      ADMIN_EMAIL: 'admin@localhost'
      ADMIN_PASSWORD: 'NeLr67Q#5z*oMD@foN79^dsQxyTEVezyG3c^v5W'
    restart: on-failure
    depends_on:
      redis:
        condition: service_healthy
  web:
    image: mediacms/mediacms:latest
    deploy:
      replicas: 1
    ports:
      - "11180:80"
    volumes:
      - /mnt/mediacms/deploy:/home/mediacms.io/mediacms/deploy
      - /mnt/mediacms/media_files:/home/mediacms.io/mediacms/media_files
      - /mnt/mediacms/logs:/home/mediacms.io/mediacms/logs
    environment:
#      ENABLE_UWSGI: 'no'
      ENABLE_CELERY_BEAT: 'no'
      ENABLE_CELERY_SHORT: 'no'
      ENABLE_CELERY_LONG: 'no'
      ENABLE_MIGRATIONS: 'no'

  celery_beat:
    image: mediacms/mediacms:latest
    volumes:
      - /mnt/mediacms/deploy:/home/mediacms.io/mediacms/deploy
      - /mnt/mediacms/media_files:/home/mediacms.io/mediacms/media_files
      - /mnt/mediacms/logs:/home/mediacms.io/mediacms/logs
    environment:
      ENABLE_UWSGI: 'no'
      ENABLE_NGINX: 'no'
      ENABLE_CELERY_SHORT: 'no'
      ENABLE_CELERY_LONG: 'no'
      ENABLE_MIGRATIONS: 'no'

  celery_worker:
    image: mediacms/mediacms:latest
    deploy:
      replicas: 1
    volumes:
      - /mnt/mediacms/deploy:/home/mediacms.io/mediacms/deploy
      - /mnt/mediacms/media_files:/home/mediacms.io/mediacms/media_files
      - /mnt/mediacms/logs:/home/mediacms.io/mediacms/logs
    environment:
      ENABLE_UWSGI: 'no'
      ENABLE_NGINX: 'no'
      ENABLE_CELERY_BEAT: 'no'
      ENABLE_MIGRATIONS: 'no'
    depends_on:
      - migrations
```
